<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="amalthea" nsURI="http://www.eclipse.org/papyrus/2017/Amalthea"
    nsPrefix="Amalthea">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="Amalthea"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Dummy"/>
  <eSubpackages name="common" nsURI="http://www.eclipse.org/papyrus/2017/Amalthea/Common"
      nsPrefix="Common">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="CommonModel"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="CustomProperty">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractTime" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          lowerBound="1" eType="#//common/TimeUnit"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_DataType" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TimeUnit">
      <eLiterals name="_undefined_"/>
      <eLiterals name="s" value="1"/>
      <eLiterals name="ms" value="2"/>
      <eLiterals name="us" value="3"/>
      <eLiterals name="ns" value="4"/>
      <eLiterals name="ps" value="5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Time" eSuperTypes="#//common/AbstractTime"/>
    <eClassifiers xsi:type="ecore:EClass" name="IAnnotatable" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Instructions" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Deviation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="distribution" ordered="false"
          lowerBound="1" eType="#//common/Distribution"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Distribution" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WeibullEstimators" eSuperTypes="#//common/Distribution">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pRemainPromille" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mean" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstructionsDeviation" eSuperTypes="#//common/Instructions">
      <eStructuralFeatures xsi:type="ecore:EReference" name="deviation" ordered="false"
          eType="#//common/Deviation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Counter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="counterOffset" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="counterPrescaler" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_DataType" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataSize">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          lowerBound="1" eType="#//common/DataUnit"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_DataType" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DataUnit">
      <eLiterals name="bit"/>
      <eLiterals name="kbit" value="1"/>
      <eLiterals name="Mbit" value="2"/>
      <eLiterals name="Gbit" value="3"/>
      <eLiterals name="Tbit" value="4"/>
      <eLiterals name="kibit" value="5"/>
      <eLiterals name="Mibit" value="6"/>
      <eLiterals name="Gibit" value="7"/>
      <eLiterals name="Tibit" value="8"/>
      <eLiterals name="byte" value="9"/>
      <eLiterals name="kB" value="10"/>
      <eLiterals name="MB" value="11"/>
      <eLiterals name="GB" value="12"/>
      <eLiterals name="TB" value="13"/>
      <eLiterals name="KiB" value="14"/>
      <eLiterals name="MiB" value="15"/>
      <eLiterals name="GiB" value="16"/>
      <eLiterals name="TiB" value="17"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="components" nsURI="http://www.eclipse.org/papyrus/2017/Amalthea/Components"
      nsPrefix="Components">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="ComponentsModel"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="FInterfacePort">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="FInterfacePort is owend port&#xD;&#xA;of Component.&#xD;&#xA;Kind is represented by isConjugate property&#xD;&#xA;of UML port&#xD;&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="runnables" ordered="false"
          upperBound="-1" eType="#//software/Runnable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Composite" eSuperTypes="#//components/Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="componentinstances" ordered="false"
          upperBound="-1" eType="#//components/ComponentInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="software" nsURI="http://www.eclipse.org/papyrus/2017/Amalthea/Software"
      nsPrefix="Software">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="SWModel"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="RunnableItem" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="RunnableItems are owned&#xD;&#xA;operations of Runnable&#xD;&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Operation" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CallSequenceItem" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="CallSequenceItems are owned&#xD;&#xA;operations of CallSequence Class&#xD;&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Operation" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="counter" ordered="false"
          eType="#//common/Counter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractElementMemoryInformation"
        abstract="true" eSuperTypes="../../org.eclipse.papyrus.sysml14/resources/profile/sysml.ecore#//blocks/Block"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractProcess" abstract="true" eSuperTypes="#//software/AbstractElementMemoryInformation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Process" abstract="true" eSuperTypes="#//software/AbstractProcess">
      <eStructuralFeatures xsi:type="ecore:EReference" name="callgraph" ordered="false"
          eType="#//software/CallGraph"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CallGraph">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graphentries" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//software/GraphEntry"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GraphEntry" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//software/Process">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="preemption" ordered="false"
          lowerBound="1" eType="#//software/Preemption"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="multipleTaskActivationLimit"
          ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Preemption">
      <eLiterals name="_undefined_"/>
      <eLiterals name="preemptive" value="1"/>
      <eLiterals name="cooperative" value="2"/>
      <eLiterals name="non_preemptive" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ISR" eSuperTypes="#//software/Process"/>
    <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//software/AbstractElementMemoryInformation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constant" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bVolatile" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="buffered" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberBits" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CallSequence" eSuperTypes="#//software/GraphEntry"/>
    <eClassifiers xsi:type="ecore:EClass" name="InterProcessActivation" eSuperTypes="#//software/CallSequenceItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="TaskRunnableCall" eSuperTypes="#//software/CallSequenceItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="runnable" ordered="false"
          lowerBound="1" eType="#//software/Runnable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LabelAccess" eSuperTypes="#//software/RunnableItem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBuffered" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" ordered="false"
          lowerBound="1" eType="#//software/LabelAccessEnum"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="data" ordered="false"
          lowerBound="1" eType="#//software/Label"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="LabelAccessEnum">
      <eLiterals name="_undefined_"/>
      <eLiterals name="read" value="1"/>
      <eLiterals name="write" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RunnableInstructions" eSuperTypes="#//software/RunnableItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="default" ordered="false"
          lowerBound="1" eType="#//common/Instructions"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Runnable" eSuperTypes="#//software/AbstractElementMemoryInformation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="callback" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="service" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="hardware" nsURI="http://www.eclipse.org/papyrus/2017/Amalthea/Hardware"
      nsPrefix="Hardware">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="HWModel"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="HwSystem" eSuperTypes="#//hardware/ComplexNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ecus" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//hardware/ECU"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="systemtype" ordered="false"
          eType="#//hardware/SystemType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexNode" abstract="true" eSuperTypes="../../org.eclipse.papyrus.sysml14/resources/profile/sysml.ecore#//blocks/Block">
      <eStructuralFeatures xsi:type="ecore:EReference" name="quartzes" ordered="false"
          upperBound="-1" eType="#//hardware/Quartz"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="prescaler" ordered="false"
          upperBound="-1" eType="#//hardware/Prescaler"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="networks" ordered="false"
          upperBound="-1" eType="#//hardware/Network"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Quartz" eSuperTypes="#//hardware/ComplexNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false"
          lowerBound="1" eType="#//hardware/QType" defaultValueLiteral="_undefined_"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="QType">
      <eLiterals name="_undefined_"/>
      <eLiterals name="DYNAMIC" value="1"/>
      <eLiterals name="STATIC" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Prescaler" eSuperTypes="../../org.eclipse.papyrus.sysml14/resources/profile/sysml.ecore#//blocks/Block">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="clockRatio" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"
          defaultValueLiteral="0.0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Network" eSuperTypes="#//hardware/ComplexNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="networktype" ordered="false"
          lowerBound="1" eType="#//hardware/NetworkType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NetworkType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="schedPolicy" ordered="false"
          lowerBound="1" eType="#//hardware/SchedType" defaultValueLiteral="_undefined_"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bitWidth" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_DataType" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SchedType">
      <eLiterals name="_undefined_"/>
      <eLiterals name="RROBIN" value="1"/>
      <eLiterals name="PRIORITY" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ECU" eSuperTypes="#//hardware/ComplexNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="microcontrollers" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//hardware/Microcontroller"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ecutype" ordered="false"
          eType="#//hardware/ECUType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Microcontroller" eSuperTypes="#//hardware/ComplexNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="cores" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//hardware/Core"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="microcontrollertype"
          ordered="false" eType="#//hardware/MicrocontrollerType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Core" eSuperTypes="#//hardware/ComplexNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lockstepGroup" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coretype" ordered="false"
          eType="#//hardware/CoreType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CoreType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bitWidth" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instructionsPerCycle"
          ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_DataType" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MicrocontrollerType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_DataType" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ECUType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_DataType" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_DataType" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bus" eSuperTypes="#//hardware/NetworkType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="busType" ordered="false"
          lowerBound="1" eType="#//hardware/BusType" defaultValueLiteral="_undefined_"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BusType">
      <eLiterals name="_undefined_"/>
      <eLiterals name="CAN" value="1"/>
      <eLiterals name="TTCAN" value="2"/>
      <eLiterals name="LIN" value="3"/>
      <eLiterals name="FLEXRAY" value="4"/>
      <eLiterals name="ETHERNET" value="5"/>
      <eLiterals name="SPI" value="6"/>
      <eLiterals name="NA" value="7"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Frequency">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Real"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" ordered="false"
          lowerBound="1" eType="#//hardware/FrequencyUnit" defaultValueLiteral="_undefined_"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FrequencyUnit">
      <eLiterals name="_undefined_"/>
      <eLiterals name="Hz" value="1"/>
      <eLiterals name="kHz" value="2"/>
      <eLiterals name="MHz" value="3"/>
      <eLiterals name="GHz" value="4"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="os" nsURI="http://www.eclipse.org/papyrus/2017/Amalthea/OperatingSystem"
      nsPrefix="Os">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="OSModel"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="OperatingSystem" eSuperTypes="../../org.eclipse.papyrus.sysml14/resources/profile/sysml.ecore#//blocks/Block">
      <eStructuralFeatures xsi:type="ecore:EReference" name="taskscheduler" ordered="false"
          upperBound="-1" eType="#//os/TaskScheduler"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interruptcontroller"
          ordered="false" upperBound="-1" eType="#//os/InterruptController"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TaskScheduler" eSuperTypes="#//os/Scheduler">
      <eStructuralFeatures xsi:type="ecore:EReference" name="schedulingalgorithm"
          ordered="false" eType="#//os/TaskSchedulingAlgorithm"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Scheduler" abstract="true" eSuperTypes="../../org.eclipse.papyrus.sysml14/resources/profile/sysml.ecore#//blocks/Block">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduleUnitPriority"
          ordered="false" lowerBound="1" eType="ecore:EDataType ../../org.eclipse.uml2.types/model/Types.ecore#//Integer"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="schedulingunit" ordered="false"
          eType="#//os/SchedulingUnit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SchedulingUnit" abstract="true" eSuperTypes="../../org.eclipse.papyrus.sysml14/resources/profile/sysml.ecore#//blocks/Block"/>
    <eClassifiers xsi:type="ecore:EClass" name="TaskSchedulingAlgorithm" abstract="true"
        eSuperTypes="../../org.eclipse.papyrus.sysml14/resources/profile/sysml.ecore#//blocks/Block"/>
    <eClassifiers xsi:type="ecore:EClass" name="InterruptController" eSuperTypes="#//os/Scheduler">
      <eStructuralFeatures xsi:type="ecore:EReference" name="schedulingalgorithm"
          ordered="false" eType="#//os/InterruptSchedulingAlgorithm"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InterruptSchedulingAlgorithm" abstract="true"
        eSuperTypes="../../org.eclipse.papyrus.sysml14/resources/profile/sysml.ecore#//blocks/Block"/>
    <eClassifiers xsi:type="ecore:EClass" name="SchedulingHWUnit" eSuperTypes="#//os/SchedulingUnit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="time" ordered="false"
          eType="#//common/Time"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OSEK" eSuperTypes="#//os/TaskSchedulingAlgorithm"/>
    <eClassifiers xsi:type="ecore:EClass" name="PriorityBased" eSuperTypes="#//os/InterruptSchedulingAlgorithm"/>
  </eSubpackages>
  <eSubpackages name="mapping" nsURI="http://www.eclipse.org/papyrus/2017/Amalthea/Mapping"
      nsPrefix="Mapping">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="MappingModel"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="MappingModel" eSuperTypes="../../org.eclipse.papyrus.sysml14/resources/profile/sysml.ecore#//blocks/Block"/>
  </eSubpackages>
  <eSubpackages name="stimuli" nsURI="http://www.eclipse.org/papyrus/2017/Amalthea/Stimuli"
      nsPrefix="Stimuli">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="StimuliModel"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Single" eSuperTypes="#//stimuli/Stimulus">
      <eStructuralFeatures xsi:type="ecore:EReference" name="activation" ordered="false"
          lowerBound="1" eType="#//common/Time"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Stimulus" abstract="true" eSuperTypes="../../org.eclipse.papyrus.sysml14/resources/profile/sysml.ecore#//blocks/Block"/>
    <eClassifiers xsi:type="ecore:EClass" name="Periodic" eSuperTypes="#//stimuli/Stimulus">
      <eStructuralFeatures xsi:type="ecore:EReference" name="recurrence" ordered="false"
          lowerBound="1" eType="#//common/Time"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="offset" ordered="false"
          lowerBound="1" eType="#//common/Time"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interprocess" eSuperTypes="#//stimuli/Stimulus">
      <eStructuralFeatures xsi:type="ecore:EReference" name="counter" ordered="false"
          lowerBound="1" eType="#//common/Counter"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="constraints" nsURI="http://www.eclipse.org/papyrus/2017/Amalthea/Constraints"
      nsPrefix="Constraints">
    <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
      <details key="originalName" value="ConstraintsModel"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="ConstraintsModel"/>
    <eClassifiers xsi:type="ecore:EClass" name="Requirement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" ordered="false"
          lowerBound="1" eType="#//constraints/Severity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="Severity">
      <eLiterals name="_undefined_"/>
      <eLiterals name="Cosmetic" value="1"/>
      <eLiterals name="Minor" value="2"/>
      <eLiterals name="Major" value="3"/>
      <eLiterals name="Critical" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessRequirement" eSuperTypes="#//constraints/Requirement"/>
    <eClassifiers xsi:type="ecore:EClass" name="RequirementLimit" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="TimeRequirementLimit" eSuperTypes="#//constraints/RequirementLimit"/>
  </eSubpackages>
</ecore:EPackage>
